services:
  - type: web
    name: lab-node
    runtime: docker
    rootDir: site-node
    plan: free

  - type: web
    name: lab-php
    runtime: docker
    rootDir: site-php
    plan: free

  - type: web
    name: lab-aspnet
    runtime: docker
    rootDir: site-aspnet
    plan: free