# upstream'ы приложений
upstream node_app { server 127.0.0.1:3001; }
upstream dotnet_app { server 127.0.0.1:5001; }

server {
    listen 80;
    server_name _;

    # Сайт №1 — Node.js (многостраничник) через прокси, на главной /
    location / {
        proxy_pass http://node_app/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Сайт №2 — PHP (одностраничник) через php-fpm
    location /php/ {
        alias /var/www/site-php/;
        index index.php;
        location ~ ^/php/(.+\.php)$ {
            alias /var/www/site-php/$1;
            fastcgi_pass unix:/run/php/php8.3-fpm.sock;
            # версию сокета проверить: ls /run/php/*.sock (8.1/8.2/8.3)
            fastcgi_param SCRIPT_FILENAME $request_filename;
            include fastcgi_params;
        }
    }

    # Сайт №3 — ASP.NET Core (Kestrel) через прокси
    location /dotnet/ {
        proxy_pass http://dotnet_app/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
    }
}
